plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

# Do not enforce documentation
Style/Documentation:
  Enabled: false

# Disabled due to complex use cases
RSpec/NestedGroups:
  Enabled: false
