name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Test
        run: bundle exec rspec

      - name: Memory test
        run: bundle exec rspec --tag speed:slow

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Lint
        run: bundle exec rubocop

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Build
        run: bundle exec rake build
